### ISSUE TITLE
Project Review: Summary

### ISSUE THREAD

**Issue by SidTheEngineer** [shca34/prj-rev-bwfs-dasmoto#1]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4/4
* _Comment(s):_ CSS file is appropriately linked to the HTML via a relative path 👍 
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_ 4/4
* _Comment(s):_ The page is pretty much spot on with respect to the design specification. All of the appropriate fonts, color, and image are included in the right spots and the structure of the site is perfect. Nice work here!
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 3.5/4 
* _Comment(s):_ Good work with your HTML. Elements are used appropriately and the file is structured well by section. The only area for improvement here is in the indentation. Within the div for each section, we've indented each element at each level. The only time we need to indent is when an element is contained by another element. So in this case, our `<h3>` and `<p>` elements do not need to be indented because they are not further contained within the div.
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 4/4
* _Comment(s):_ Your CSS is pretty much spot on with the solution. You've kept things clean/consise and I don't see any issues with the syntax. The site is styled perfectly. Nice work 👍 
 
### Overall Score: 15.5/16 🔥 🎉 
Awesome work!

**Comment by shca34** [comment]
Thanks for the comprehensive feedback!
